/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managescale;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import network.NetworkHandler;

/**
 * @author train
 */
public class JoinFrame extends javax.swing.JFrame {
    /**
     * Creates new form joinFrame
     */
       ///////////주환 수정
    public static boolean juhwan;
    //////////////////////
    public JoinFrame() {
        initComponents();
        
        buttonGroup1.add(man_radio_button);
        buttonGroup1.add(women_radio_button);
        
        this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
             System.out.println("Join closing");
             e.getWindow().dispose();
            }         
        });
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        man_radio_button = new javax.swing.JRadioButton();
        women_radio_button = new javax.swing.JRadioButton();
        complete_Btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pwd_edit_panel = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        id_edit_panel = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        name_edit_panel = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        birthday_edit_panel = new javax.swing.JEditorPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        phoneN_edit_panel = new javax.swing.JEditorPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        weight_edit_panel = new javax.swing.JEditorPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        nickname_edit_panel = new javax.swing.JEditorPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        height_edit_panel = new javax.swing.JEditorPane();
        overlapNickName_btn = new javax.swing.JButton();
        overlapID_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textField1.setText("textField1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField1.setText("             회원 가입");

        jTextField2.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField2.setText("아 이 디");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField3.setText("비밀번호");

        jTextField4.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField4.setText(" 이    름");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField5.setText("전화번호");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField6.setText(" 닉 네 임");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField7.setText(" 성    별 ");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField8.setText("생년월일");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jTextField9.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField9.setText(" 몸 무 게");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField10.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jTextField10.setText("     키");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        man_radio_button.setBackground(new java.awt.Color(255, 255, 255));
        man_radio_button.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        man_radio_button.setText("   남 자");

        women_radio_button.setBackground(new java.awt.Color(255, 255, 255));
        women_radio_button.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        women_radio_button.setText("   여 자");

        complete_Btn.setBackground(new java.awt.Color(255, 255, 255));
        complete_Btn.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        complete_Btn.setText("완   료");
        complete_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complete_BtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(pwd_edit_panel);

        jScrollPane4.setViewportView(id_edit_panel);

        jScrollPane5.setViewportView(name_edit_panel);

        jScrollPane6.setViewportView(birthday_edit_panel);

        jScrollPane7.setViewportView(phoneN_edit_panel);

        jScrollPane8.setViewportView(weight_edit_panel);

        jScrollPane9.setViewportView(nickname_edit_panel);

        jScrollPane10.setViewportView(height_edit_panel);

        overlapNickName_btn.setText("중복체크");
        overlapNickName_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overlapNickName_btnActionPerformed(evt);
            }
        });

        overlapID_btn.setText("중복체크");
        overlapID_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overlapID_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField9)
                            .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(man_radio_button)
                                .addGap(18, 18, 18)
                                .addComponent(women_radio_button))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(overlapNickName_btn)
                                    .addComponent(overlapID_btn))))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(complete_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jScrollPane4)
                    .addComponent(overlapID_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(overlapNickName_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(man_radio_button)
                        .addComponent(women_radio_button)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField10)
                    .addComponent(jScrollPane10))
                .addGap(64, 64, 64)
                .addComponent(complete_Btn)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    //입력에 대한 예외처리 해야함
    private void complete_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complete_BtnActionPerformed
        // TODO add your handling code here:
        String id = id_edit_panel.getText(); //email 
        String pwd = pwd_edit_panel.getText();
        String name = name_edit_panel.getText();
        String phoneNumber = phoneN_edit_panel.getText();
        String nickName = nickname_edit_panel.getText();
        
        //1 남자, 2 여자
        String sex = null;
        if(man_radio_button.isSelected()){
            sex = "M"; 
        }else if(women_radio_button.isSelected()){
            sex = "F";
        }
       
        String birth = birthday_edit_panel.getText();
        String weight = weight_edit_panel.getText();
        String height = height_edit_panel.getText();      
        
        System.out.println(id+","+ pwd+","+ name+","+ phoneNumber+","+ nickName+","+ sex+","+ birth+","+ weight+","+ height);
              
        String result = NetworkHandler.join(id, pwd, name, phoneNumber, nickName, sex, birth,weight,height);
        
        System.out.println(result);                     
//        NetworkHandler.join(id, pwd, name, phoneNumber, nickName, sex, birth, weight, height);
    }//GEN-LAST:event_complete_BtnActionPerformed

    private void overlapID_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overlapID_btnActionPerformed
        // TODO add your handling code here:
        //email 형식 확인
        String id = id_edit_panel.getText();
        
         if(!id.equals("")){
            String result = NetworkHandler.id_check(id);
          
            ///////////주환 수정
            if(juhwan == true){
            JOptionPane.showMessageDialog(null,"id check :" + result);
            }
            juhwan = true;
            /////////////////////
            System.out.println("id check : "+result);
        }else{
            System.out.println("입력하세요");
            ///////////주환 수정
            JOptionPane.showMessageDialog(null,"입력하세요");
            ////////////////////
        }
    }//GEN-LAST:event_overlapID_btnActionPerformed

    private void overlapNickName_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overlapNickName_btnActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        //email 형식 확인
        String NickString = nickname_edit_panel.getText();
        
        if(!NickString.equals("")){
            String result = NetworkHandler.nickName_check(NickString);
            System.out.println(result);
        }else{
            System.out.println("nickname check : "+"입력하세요");
        }
    }//GEN-LAST:event_overlapNickName_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane birthday_edit_panel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton complete_Btn;
    private javax.swing.JEditorPane height_edit_panel;
    private javax.swing.JEditorPane id_edit_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JRadioButton man_radio_button;
    private javax.swing.JEditorPane name_edit_panel;
    private javax.swing.JEditorPane nickname_edit_panel;
    private javax.swing.JButton overlapID_btn;
    private javax.swing.JButton overlapNickName_btn;
    private javax.swing.JEditorPane phoneN_edit_panel;
    private javax.swing.JEditorPane pwd_edit_panel;
    private java.awt.TextField textField1;
    private javax.swing.JEditorPane weight_edit_panel;
    private javax.swing.JRadioButton women_radio_button;
    // End of variables declaration//GEN-END:variables
}
