/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managescale;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import network.NetworkHandler;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

import org.apache.http.ParseException;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import uclab.ui.MainJFrame;
/**
 * @author train
 */
public class TotalFrame extends javax.swing.JFrame {
 
    
    String Time1;

           Date ConvertCurrent;
    
    
    /**
     * Creates new form joinFrame
     */
    public TotalFrame() {
        initComponents();
        
        ListData();
  
        this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
             System.out.println("start closing");
             e.getWindow().dispose();
            }         
        });
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jButton1.setText("시 작");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jButton2.setText("조 회");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("굴림", 0, 18)); // NOI18N
        jButton3.setText("정 보");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame fs = new MainJFrame();
        fs.setLocationRelativeTo(null);
        fs.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JFrame fs = new SearchFrame();
        fs.setLocationRelativeTo(null);
        fs.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ListData(){
        
       SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd",Locale.KOREA);
      
       Date currentTime  = new Date();
       
       SimpleDateFormat f2 = new SimpleDateFormat("yyyy-MM-dd",Locale.KOREA);      
      
       try{

          Time1 = f2.format(currentTime);
           
           SimpleDateFormat transFormat = new SimpleDateFormat("yyyy-MM-dd");
           
           ConvertCurrent = transFormat.parse(Time1);
           
           
           System.out.println("MTIME : " + currentTime);
           System.out.println("이제 되자 : " + ConvertCurrent);
           
       }catch(ParseException e){
           e.printStackTrace();
       } catch (java.text.ParseException ex) {
            Logger.getLogger(SearchFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
 
       String result = NetworkHandler.search_check(); 
       
       DefaultListModel listModel = new DefaultListModel(); 
       
       listModel.removeAllElements(); 
        
//       listModel.addElement(result);
//                      
//       jList1.setModel(listModel);
//         
       try{
            JSONObject json = new JSONObject(result);

            JSONArray jArr = json.getJSONArray("wList");
            
            System.out.println("JARRRRRR : " + jArr);
            
            String[] name = {"createDate","bmi","fatPer","fatMass"};

            for(int i = 0; i< jArr.length(); i++){
                json = jArr.getJSONObject(i); 
                   
                String createDate = json.getString("createDate").toString();
                
                String bmi = json.getString("bmi").toString();
                
                String fatPer = json.getString("fatPer").toString();
                
                String fatMass = json.getString("fatMass").toString();
               
                String subdate = createDate.substring(0,10);
                
                SimpleDateFormat f3 = new SimpleDateFormat("yyyy-MM-dd",Locale.KOREA); 
                
                try{
                    Date ddd = f3.parse(createDate);
                    
                    System.out.println("createDate : " + ddd);
                    
                    
                    if(ddd.equals(ConvertCurrent)){
                        
                        listModel.addElement("Date : " + subdate + " bmi : "+ bmi + " fatPer : "+fatPer + " fatMass : "+fatMass);
                           jList1.setModel(listModel);
                       
                    }
 
                }catch(ParseException e){
                        e.printStackTrace();
                    } catch (java.text.ParseException ex) {
                         Logger.getLogger(SearchFrame.class.getName()).log(Level.SEVERE, null, ex);
                     }
            }
            
            
 
       }catch(JSONException e){
           e.printStackTrace();

       }
  
    }  
   
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
